# Generated by Django 3.2.9 on 2021-11-25 04:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_review_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rank',
            field=models.PositiveIntegerField(default=1, help_text='1~10사이 값으로 입력하세요', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
